name: Debug Discord

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test curl
        run: |
          echo "TESTE INICIADO"
          curl -v -X POST ${{ secrets.DISCORD_WEBHOOK }} \
          -H "Content-Type: application/json" \
          -d '{"content":"🔥 TESTE DIRETO DO GITHUB ACTIONS"}'
